version: 0.1.{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '1.1'
  package_version: '1.1'
  assembly_version: '1.1'
  file_version: '1.1'
  informational_version: '1.1'
clone_script:
  - cmd: git clone -q --recurse-submodules --branch=%APPVEYOR_REPO_BRANCH% https://github.com/TJYSunset/HardFuzz %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
before_build:
  - nuget restore
build:
  project: HardFuzz.sln
  publish_nuget: true
  verbosity: minimal
before_test:
  - ps: cp C:\projects\hardfuzz\HardFuzz.Test\TestData\* C:\projects\hardfuzz\HardFuzz.Test\bin\Release\netcoreapp3.1\
  - ps: ls C:\projects\hardfuzz\HardFuzz.Test\bin\Release\netcoreapp3.1\
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    server:
    api_key:
      secure: ccflV/crOw54DXpeWcY4lH+CoITGN++nCbKj8UJ5o2Uei53UUmH+GxDfveg6R78C
    skip_symbols: false
    symbol_server:
    artifact: /.*\.nupkg/
